name: PHPStan

on:
    workflow_call:
        inputs:
            PHP_VERSION:
                description: PHP version which PHPStan will be executed on.
                default: '8.1'
                required: false
                type: string

jobs:
    phpstan:
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: shivammathur/setup-php@v2
            with:
                php-version: ${{ inputs.PHP_VERSION }}
                tools: composer, cs2pr
                coverage: none
          - run: composer validate
          - uses: ramsey/composer-install@v3
            with:
                composer-options: '--prefer-dist'
          - run: ./vendor/bin/phpstan analyse --no-progress --memory-limit=1G
